services:
  fundamentals:
    image: node:latest
    working_dir: /app
    command: sh -c "npm run build && node /app/index.js"
    volumes:
      - ./:/app
      - ./files:/app/files
    ports:
      - 3300:3000